# Generated by Django 5.1 on 2024-08-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdOps', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='adderess',
            new_name='address',
        ),
    ]
